name: CI/CD Pipeline PHP App

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/myphp-app:latest .

    # 3. Login ke GitHub Container Registry
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4. Push image ke GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/myphp-app:latest
